title: Massachusetts General Hospital: Patient Encounter & Cost Analysis Report
logo: #path to picture 
show_download: false
remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
